name: joris
description: app for watching funny Chuck Norris jokes

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^2.17.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  dio: ^4.0.6
  firebase_crashlytics: ^2.8.2
  firebase_core: ^1.18.0
  firebase_database: ^9.0.16
  json_serializable: ^6.3.1
  json_annotation: ^4.6.0
  build_runner: ^2.1.11
  get: ^4.6.5
  convert: ^3.0.2
  cloud_firestore: ^3.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.9.2

flutter:
  uses-material-design: true
  assets:
    - lib/assets/

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "lib/assets/joris_app_logo.png"
