// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlBjGjD4PBpMIbRodnlyUietFXj1OEi20',
    appId: '1:1090403958808:web:93305b00a08e49fe1f036d',
    messagingSenderId: '1090403958808',
    projectId: 'joris-90061',
    authDomain: 'joris-90061.firebaseapp.com',
    storageBucket: 'joris-90061.appspot.com',
    measurementId: 'G-T6V7R27VEQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOR5H6Erkc72yMEJ68XfG6F8FsbxnQ5wk',
    appId: '1:1090403958808:android:2a044c839da877021f036d',
    messagingSenderId: '1090403958808',
    projectId: 'joris-90061',
    storageBucket: 'joris-90061.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqfAPepDvyWshs-4V7SB3iSpl6M8CsJzA',
    appId: '1:1090403958808:ios:04a682446e2ca8441f036d',
    messagingSenderId: '1090403958808',
    projectId: 'joris-90061',
    storageBucket: 'joris-90061.appspot.com',
    iosClientId: '1090403958808-18c29snl9segm1re17cpqmueo192n5vs.apps.googleusercontent.com',
    iosBundleId: 'com.example.joris',
  );
}
